server:
  port: 8762
  #port: 8763
#服务客户端，实际的业务项目
spring:
  application:
    name: eureka-client

eureka:
  instance:
    metadata-map:
      cluster: EurekaClient #集群名
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/