eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8988
#分布式数据链路跟踪客户端1
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: zipkin-client1