eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
#路由网关，转发、过滤器。
spring:
  application:
    name: zuul
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: ribbon
    feign:
      path: /feign/**
      serviceId: feign