server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#配置中心，服务端
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nieyue/spring-cloud-config/
          search-paths: test
          username: nieyue
          password: xxxx
      label: master
