eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
#融合了Hystrix断路器的Feign服务消费者，具有熔断、负载均衡的能力。
spring:
  application:
    name: feign
feign:
  hystrix:
    enabled: true